### ISSUE TITLE
installation seemingly broken

### ISSUE THREAD

**Issue by adf-ncgr** [ncgr/bionorm#8]
followed recommended pipx installation on haldane; result:
[adf@haldane ~]$bionorm
Traceback (most recent call last):
  File "/home/localhost/adf/.local/bin/bionorm", line 5, in <module>
    from bionorm import cli
  File "/home/localhost/adf/.local/pipx/venvs/bionorm/lib/python3.8/site-packages/bionorm/__init__.py", line 84, in <module>
    from .installer import install  # isort:skip
  File "/home/localhost/adf/.local/pipx/venvs/bionorm/lib/python3.8/site-packages/bionorm/installer.py", line 13, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by joelb123** [comment]
Ah, I missed a non-developer dependency.  Fixed in version 0.3.2, which I just pushed.

**Comment by joelb123** [comment]
Fixed by 55c9bd3
